# Generated by Django 4.1.1 on 2022-10-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('birth', models.DateField(verbose_name='Date of Birth')),
                ('nationality', models.CharField(max_length=200, verbose_name='Nationality')),
            ],
        ),
    ]
