# Generated by Django 4.1.1 on 2022-10-10 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.CharField(max_length=250, verbose_name='Film')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('director', models.CharField(max_length=250, verbose_name='Director')),
                ('rating', models.IntegerField(default=5, help_text='value 1 to 10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
