# Generated by Django 4.1.1 on 2022-10-16 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_film_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='director',
        ),
        migrations.AlterField(
            model_name='rating',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.film'),
        ),
    ]
