# Generated by Django 4.1.1 on 2022-10-16 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_rating_director_alter_rating_film'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='year',
        ),
    ]
