# Generated by Django 4.1.1 on 2022-10-16 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_rating_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentals',
            name='rented_film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.film'),
        ),
    ]
