# Generated by Django 4.1.1 on 2022-10-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_rentals_rented_film'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rentals',
            new_name='Rental',
        ),
    ]
